In [1]:
import pandas as pd
dataset = pd.read_csv('Tweets.csv')

In [2]:
dataset.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [3]:
data = dataset[['text','airline_sentiment']]
data.head()

                                                text airline_sentiment
0                @VirginAmerica What @dhepburn said.           neutral
1  @VirginAmerica plus you've added commercials t...          positive
2  @VirginAmerica I didn't today... Must mean I n...           neutral
3  @VirginAmerica it's really aggressive to blast...          negative
4  @VirginAmerica and it's a really big bad thing...          negative

In [4]:
data.shape

(14640, 2)

In [5]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /home/knightfury2412/miniconda3/envs/mlenv/lib/python3.13/site-packages (from gensim) (2.2.6)
Requirement already satisfied: scipy>=1.7.0 in /home/knightfury2412/miniconda3/envs/mlenv/lib/python3.13/site-packages (from gensim) (1.16.3)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.6.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: wrapt in /home/knightfury2412/miniconda3/envs/mlenv/lib/python3.13/site-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 2.0 MB/s  0:00:14m0:00:0100:01
Downloading smart_open-7.6.0-py3-none-any.whl (64 kB)
Installing collected packages: smart_open, gensim
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [gensim]2m1/2 [gensim]
Successfully installed gensim-4.4.0 smart_open-7.6.0

In [6]:
import gensim.downloader

In [7]:
glove_wv = gensim.downloader.load('glove-twitter-200')
glove_wv

[==================================================] 100.0% 758.5/758.5MB downloaded

In [ ]:
import re

def clean_text(text):
    text = re.sub(r'[^a-z@]'," ",text.lower())
    return text.split()

In [ ]:

def doc_vec(doc):
    return glove_wv.get_mean_vector(doc)

In [8]:
X = data[['text']]
y = data['airline_sentiment']

In [ ]:
X_transformed = X.apply(doc_vec)
X_transformed.shape